load("@rules_python//python:py_library.bzl", "py_library")

py_library(
    name = "lib",
    imports = [".."],
    visibility = ["//backend/py:__subpackages__"],
    deps = [
        ":action",
        ":action_filter",
        ":profile",
        ":profile_event_classifier",
        ":profile_loader",
        ":thread",
    ],
)

py_library(
    name = "action_filter",
    srcs = ["action_filter.py"],
)

py_library(
    name = "action",
    srcs = ["action.py"],
    deps = [":profile_event_classifier"],
)

py_library(
    name = "profile_event_classifier",
    srcs = ["profile_event_classifier.py"],
)

py_library(
    name = "profile_loader",
    srcs = ["profile_loader.py"],
)

py_library(
    name = "profile",
    srcs = ["profile.py"],
    deps = [
        ":action",
        ":action_filter",
        ":profile_event_classifier",
        ":profile_loader",
        ":thread",
    ],
)

py_library(
    name = "thread",
    srcs = ["thread.py"],
    deps = [
        ":action",
        ":profile_event_classifier",
    ],
)
