load("@rules_python//python:py_binary.bzl", "py_binary")

py_binary(
    name = "cli",
    srcs = ["cli.py"],
    imports = ["."],
    deps = [
        "//backend/py/src:lib",
        "@uv//:typer",
    ],
)

py_binary(
    name = "server",
    srcs = ["server.py"],
    imports = ["."],
    deps = [
        "//backend/py/src:lib",
        "//protobuf:build_event_stream_grpc",
        "//protobuf:build_event_stream_proto",
        "//protobuf:publish_build_event_grpc",
        "//protobuf:publish_build_event_proto",
        "@uv//:googleapis-common-protos",
        "@uv//:grpcio",
        "@uv//:protobuf",
    ],
)
